version: '3'
services:
  redis:
    image: redis:alpine
    ports:
      - 6379:6379
  mysql:
    image: mysql:5.7
    environment:
      - MYSQL_RANDOM_ROOT_PASSWORD=yes
      - MYSQL_DATABASE=mysql
      - MYSQL_USER=homestead
      - MYSQL_PASSWORD=password
    ports:
      - 3306:3306